[build]
command = "pip install -r requirements-netlify.txt --no-cache-dir && npm ci --prefer-offline --no-audit --progress=false --no-fund --ignore-scripts && cd web-app && npm ci --prefer-offline --no-audit --progress=false --no-fund && npm run build"
publish = "web-app/dist"
functions = "netlify/functions"

[build.environment]
PYTHON_VERSION = "3.9"
NODE_OPTIONS = "--max_old_space_size=2048"
NPM_FLAGS = "--prefer-offline --no-audit --progress=false"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/webhook"
to = "/.netlify/functions/webhook"
status = 200

[[redirects]]
from = "/stripe-webhook"
to = "/.netlify/functions/stripe-webhook"
status = 200

[[redirects]]
from = "/worker/static/*"
to = "/worker/static/:splat"
status = 200

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["python-telegram-bot", "stripe"]
included_files = ["**/*.py", "**/*.txt", "requirements*.txt"]

# Increase function timeout and memory for better performance
[functions.webhook]
included_files = ["bot/**", "worker/**", "api/**", "*.py", "*.txt"]
timeout = 30
memory = 1024
# Add proper environment variable configuration
[functions.webhook.environment]
NODE_ENV = "production"
VERSION = "1.0.0"

[functions.analyze]
included_files = ["bot/**", "worker/**", "api/**", "*.py", "*.txt"]
timeout = 30
memory = 1024

[dev]
framework = "#custom"
command = "python -m uvicorn api.main:app --reload"
targetPort = 8000